config/routes.rb
Harpcolumn::Application.routes.draw do

  resources :memberships

  resources :groups

  resources :roles

  resources :entries

  resources :notebooks

  resources :difficulties

  resources :performances

  resources :pieces
  resources :pictures
  # TODO: This stub functionality was to test the backend- we need better RESTful routing
  match "/pictures/:id/add_user/:user_slug" => "pictures#add_user"
  match "/pictures/:id/del_user/:user_slug" => "pictures#del_user"
  resources :sound_clips
  match "/sound_clips/:id/add_user/:user_slug" => "sound_clips#add_user"
  match "/sound_clips/:id/del_user/:user_slug" => "sound_clips#del_user"
  resources :venues
  devise_for :users
  resources :users
  resources :addresses
  resources :instruments
  resources :manufacturers

  root :to => "home#index"

end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  rails_admin
  
  has_many :entries
  belongs_to  :user
  
  validates_presence_of :user
  
  def notebook_type
    "Practice Journal" #we need some logic here to spell out what sort notebook this is based upon privacy, associations, etc.
  end
  
end

app/controllers/notebooks_controller.rb
class NotebooksController < InheritedResources::Base
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_for(@notebook) do |f| %>
  <% if @notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% @notebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Editing notebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<h1>Listing notebooks</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notebooks.each do |notebook| %>
  <tr>
    <td><%= notebook.name %></td>
    <td><%= link_to 'Show', notebook %></td>
    <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
    <td><%= link_to 'Destroy', notebook, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New notebook</h1>

<%= render 'form' %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @notebook.name %>
</p>


<%= link_to 'Edit', edit_notebook_path(@notebook) %> |
<%= link_to 'Back', notebooks_path %>