config/routes.rb
Harpcolumn::Application.routes.draw do

  resources :memberships

  resources :groups

  resources :roles

  resources :entries

  resources :notebooks

  resources :difficulties

  resources :performances

  resources :pieces
  resources :pictures
  # TODO: This stub functionality was to test the backend- we need better RESTful routing
  match "/pictures/:id/add_user/:user_slug" => "pictures#add_user"
  match "/pictures/:id/del_user/:user_slug" => "pictures#del_user"
  resources :sound_clips
  match "/sound_clips/:id/add_user/:user_slug" => "sound_clips#add_user"
  match "/sound_clips/:id/del_user/:user_slug" => "sound_clips#del_user"
  resources :venues
  devise_for :users
  resources :users
  resources :addresses
  resources :instruments
  resources :manufacturers

  root :to => "home#index"

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  belongs_to :role

  scope :by_user, lambda { |user|
    where('user_id = ?', user.id)
  }
  scope :by_group, lambda { |group|
    where('group_id = ?', group.id)
  }
  scope :by_role, lambda { |role|
    where('role_id = ?', role.id)
  }
end

app/controllers/memberships_controller.rb
class MembershipsController < InheritedResources::Base
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br />
    <%= f.text_field :role_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <tr>
    <th>User</th>
    <th>Group</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberships.each do |membership| %>
  <tr>
    <td><%= membership.user_id %></td>
    <td><%= membership.group_id %></td>
    <td><%= membership.role_id %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @membership.user_id %>
</p>

<p>
  <b>Group:</b>
  <%= @membership.group_id %>
</p>

<p>
  <b>Role:</b>
  <%= @membership.role_id %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>