config/routes.rb
Harpcolumn::Application.routes.draw do

  resources :memberships

  resources :groups

  resources :roles

  resources :entries

  resources :notebooks

  resources :difficulties

  resources :performances

  resources :pieces
  resources :pictures
  # TODO: This stub functionality was to test the backend- we need better RESTful routing
  match "/pictures/:id/add_user/:user_slug" => "pictures#add_user"
  match "/pictures/:id/del_user/:user_slug" => "pictures#del_user"
  resources :sound_clips
  match "/sound_clips/:id/add_user/:user_slug" => "sound_clips#add_user"
  match "/sound_clips/:id/del_user/:user_slug" => "sound_clips#del_user"
  resources :venues
  devise_for :users
  resources :users
  resources :addresses
  resources :instruments
  resources :manufacturers

  root :to => "home#index"

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  rails_admin
  acts_as_taggable
  acts_as_taggable_on :kind
  has_friendly_id :guid, :use_slug => true

  belongs_to :manufacturer
  belongs_to :user

  has_and_belongs_to_many :players, :class_name => "User"
  has_many  :picture_links,   :as    => :imageable
  has_many  :sound_clips,     :as => :soundable
  has_and_belongs_to_many :entries
  has_and_belongs_to_many :performances

  validates_presence_of   :guid
  validates_uniqueness_of :guid
  before_validation :generate_guid

  private

  def generate_guid
    self.guid = UUIDTools::UUID.random_create.to_str
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < InheritedResources::Base
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br />
    <%= f.text_field :manufacturer_id %>
  </div>
  <div class="field">
    <%= f.label :instrument_type_id %><br />
    <%= f.text_field :instrument_type_id %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :serial %><br />
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :prev_owner %><br />
    <%= f.text_field :prev_owner %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :finish %><br />
    <%= f.text_field :finish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<h1>Listing instruments</h1>

<table>
  <tr>
    <th>Model</th>
    <th>Manufacturer</th>
    <th>Purchase date</th>
    <th>Color</th>
    <th>Serial</th>
    <th>Prev owner</th>
    <th>Description</th>
    <th>Finish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instruments.each do |instrument| %>
  <tr>
    <td><%= instrument.model %></td>
    <td><%= instrument.manufacturer_id %></td>
    <td><%= instrument.purchase_date %></td>
    <td><%= instrument.color %></td>
    <td><%= instrument.serial %></td>
    <td><%= instrument.prev_owner %></td>
    <td><%= instrument.description %></td>
    <td><%= instrument.finish %></td>
    <td><%= link_to 'Show', instrument %></td>
    <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
    <td><%= link_to 'Destroy', instrument, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Model:</b>
  <%= @instrument.model %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @instrument.manufacturer_id %>
</p>

<p>
  <b>GUID:</b>
  <%= @instrument.guid %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @instrument.purchase_date %>
</p>

<p>
  <b>Color:</b>
  <%= @instrument.color %>
</p>

<p>
  <b>Serial:</b>
  <%= @instrument.serial %>
</p>

<p>
  <b>Owner:</b>
  <%= @instrument.user %>
</p>

<p>
  <b>Prev owner:</b>
  <%= @instrument.prev_owner %>
</p>

<p>
  <b>Description:</b>
  <%= @instrument.description %>
</p>

<p>
  <b>Finish:</b>
  <%= @instrument.finish %>
</p>


<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>